/**
 * Flex Work
 * This is the REST API Documentation for ICBC Flex Work, by Team Flex
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Body model module.
 * @module model/Body
 * @version 0.0.3
 */
class Body {
    /**
     * Constructs a new <code>Body</code>.
     * @alias module:model/Body
     * @param startDate {Date} 
     * @param endDate {Date} 
     * @param workspaceId {String} 
     */
    constructor(startDate, endDate, workspaceId) { 
        
        Body.initialize(this, startDate, endDate, workspaceId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startDate, endDate, workspaceId) { 
        obj['startDate'] = startDate;
        obj['endDate'] = endDate;
        obj['workspaceId'] = workspaceId;
    }

    /**
     * Constructs a <code>Body</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Body} obj Optional instance to populate.
     * @return {module:model/Body} The populated <code>Body</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body();

            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
            }
            if (data.hasOwnProperty('endDate')) {
                obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
            }
            if (data.hasOwnProperty('workspaceId')) {
                obj['workspaceId'] = ApiClient.convertToType(data['workspaceId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} startDate
 */
Body.prototype['startDate'] = undefined;

/**
 * @member {Date} endDate
 */
Body.prototype['endDate'] = undefined;

/**
 * @member {String} workspaceId
 */
Body.prototype['workspaceId'] = undefined;






export default Body;

