/**
 * Flex Work
 * This is the REST API Documentation for ICBC Flex Work, by Team Flex
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User from './User';

/**
 * The BookingSummary model module.
 * @module model/BookingSummary
 * @version 0.0.3
 */
class BookingSummary {
    /**
     * Constructs a new <code>BookingSummary</code>.
     * @alias module:model/BookingSummary
     */
    constructor() { 
        
        BookingSummary.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BookingSummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BookingSummary} obj Optional instance to populate.
     * @return {module:model/BookingSummary} The populated <code>BookingSummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BookingSummary();

            if (data.hasOwnProperty('bookingId')) {
                obj['bookingId'] = ApiClient.convertToType(data['bookingId'], 'Number');
            }
            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
            }
            if (data.hasOwnProperty('endDate')) {
                obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = User.constructFromObject(data['user']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} bookingId
 */
BookingSummary.prototype['bookingId'] = undefined;

/**
 * @member {Date} startDate
 */
BookingSummary.prototype['startDate'] = undefined;

/**
 * @member {Date} endDate
 */
BookingSummary.prototype['endDate'] = undefined;

/**
 * @member {module:model/User} user
 */
BookingSummary.prototype['user'] = undefined;






export default BookingSummary;

